version: '3'
services:
  db:
    image: postgres:16-alpine
    ports:
      - "${PORT_DB}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
