version: '3.8'
services:
  db:
    image: postgres:16-alpine
    ports:
      - "${PORT_DB}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]


  server:
    build: .
    ports:
      - "${PORT}:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ROCKET_ADDRESS=0.0.0.0
    depends_on:
      db:
        condition: service_healthy
    
volumes:
  db_data:
    driver: local
