services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mynetwork
  nginx:
    image: nginx:1.25.4-alpine-slim
    volumes:
      - ./.docker/nginx/:/etc/nginx/conf.d/
      - .:/var/www/html
    ports:
      - "${PORT}:${PORT}"
    networks:
      - mynetwork

networks:
  mynetwork: