services:
  # Choisir entre "development" ou "production" dans targer
  server:
    build:
      context: ./server
      target: development
      dockerfile: Dockerfile

  # Client par défaut la production
  client:
    build:
      context: ./client
      target: production
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"

  # Developpement
  client-dev:
    build:
      context: ./client
      target: development
      dockerfile: Dockerfile
    ports:
      - "${PORT}:5173"

    # Preprod
  client-preprod:
    build:
      context: ./client
      target: preview
      dockerfile: Dockerfile
    ports:
      - "${PORT}:4173"
